"""
Regenerate **canonical manuscript figures** and write **publication** copies under
``figures/publication/`` (mirroring subpaths under ``figures/`` when the PNG lives there).

Each panel is saved as:

- Primary **PNG** (same as the usual figure scripts).
- **PDF** (vector).
- **TIFF** — default **300 dpi** (``--publication-tiff-kind color``); use ``line`` for **1200 dpi**
  line-art style exports (see ``manuscript/figure_export.py``).

**NetMHC Fig 5–6** (merged ``*_with_iedb.tsv``):

- **5A–5C:** default coding cohort = **proportional whole-proteome** sample (length-matched
  windows). A second run emits **5C** for **random coding fragments**
  (``netmhcpan_coding_control_with_iedb.tsv``); repo mirrors for that cohort live under
  ``figures/supplementary/netmhc/coding_fragments_random_sample/``.
- **5D–5E:** **proportional whole** mirrors to ``figures/``; **random fragments** mirrors to the
  same supplementary NetMHC folder (5D is identical to the canonical sig-lnc panel; 5E uses the
  fragment merged coding TSV).

**Catalog** (Fig 1B, 2, 3, 4A): same orchestration as ``generate_catalog_figures.py`` (both
``tcga_matrix`` and ``all_smprot_filtered`` when the all-filtered FASTA exists). Mode-specific
tables and PNGs default to ``figures/supplementary/<mode>/``; canonical ``fig2b`` / ``fig3a`` /
``fig3b`` / Fig 3C (TCGA) / 3D / 4A remain under ``figures/`` as applicable.

**Supplement PCA** (same expression matrix as Fig 1B): ``supplement/plot_supplement_pca_stage_samples.py``
writes four panels under ``figures/supplementary/pca/`` unless ``--skip-supplement-pca``.

**Fig 1B:** default ``sklearn2_pca34`` writes **two** PNGs (2D t-SNE dims 1–2 only) under ``figures/``.
``--embedding opentsne4`` writes four t-SNE panels. The **PCA supplement** (``figS_pca_*``) is a
separate script under ``figures/supplementary/pca/``.

**Fig 6:** by default only **instances** split panels under ``figures/``. Pass
``--include-fig6-unique-split`` to also emit **unique** split panels under
``figures/supplementary/figure6_ttn_as1/`` (with publication PDF/TIFF mirrored for both).

**Fig 5–6 NetMHC supplement tree** (1D + LOO, Cartesian grids, TTN sweeps): not regenerated by this
script—run ``python generate_netmhc_fig5_fig6_supplement.py`` first if you need PDF/TIFF for those
paths (or extend this exporter later).

Usage::

    python export_publication_figures.py
    python export_publication_figures.py --strict
    python export_publication_figures.py --only tcga_matrix
    python export_publication_figures.py --skip-netmhc
    python export_publication_figures.py --skip-supplement-pca
    python export_publication_figures.py --include-fig6-unique-split
"""
from __future__ import annotations

import argparse
import sys

from orchestrate_subprocess import call_echo
from repo_paths import (
    DATA,
    FIGURES,
    FIGURES_PUBLICATION,
    FIGURES_SUPPLEMENTARY_FIG6_TTN,
    FIGURES_SUPPLEMENTARY_NETMHC_CODING_FRAGMENTS,
    FIGURES_SUPPLEMENTARY_PCA,
    MANUSCRIPT_DIR,
    NETMHC_DATA,
    REPO_ROOT,
    SUPPLEMENT_DIR,
)

MS = MANUSCRIPT_DIR
SUP = SUPPLEMENT_DIR
ALL_FILTERED_FAA = DATA / "smprot_all_filtered_peptides.faa"


def run_script(script: str, extra: list[str]) -> int:
    cmd = [sys.executable, str(MS / script), *extra]
    return call_echo(cmd, cwd=REPO_ROOT)


def run_supplement_script(script: str, extra: list[str]) -> int:
    cmd = [sys.executable, str(SUP / script), *extra]
    return call_echo(cmd, cwd=REPO_ROOT)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero if any subprocess fails.",
    )
    ap.add_argument(
        "--only",
        choices=("tcga_matrix", "all_smprot_filtered", "both"),
        default="both",
        help="Which peptide mode(s) for catalog figures (default: both).",
    )
    ap.add_argument(
        "--skip-netmhc",
        action="store_true",
        help="Skip Fig 5–6 NetMHC steps (only catalog 1B–4A).",
    )
    ap.add_argument(
        "--skip-supplement-pca",
        action="store_true",
        help="Skip supplement/plot_supplement_pca_stage_samples.py (PCA panels under figures/supplementary/pca/).",
    )
    ap.add_argument(
        "--publication-tiff-kind",
        choices=("line", "color"),
        default="color",
        help="Passed to each script: TIFF dpi (default color=300).",
    )
    ap.add_argument(
        "--include-fig6-unique-split",
        action="store_true",
        help="After Fig 6 instances under figures/, also write unique split panels under "
        "figures/supplementary/figure6_ttn_as1/ (default: off).",
    )
    args = ap.parse_args()

    pub = str(FIGURES_PUBLICATION)
    pub_flags = ["--publication-dir", pub, "--publication-tiff-kind", args.publication_tiff_kind]

    failures: list[tuple[str, str, int]] = []

    modes: list[str]
    if args.only == "both":
        modes = ["tcga_matrix", "all_smprot_filtered"]
    else:
        modes = [args.only]

    code_1b = run_script("plot_figure1b_tsne_stage_lncrna.py", pub_flags)
    if code_1b != 0:
        failures.append(("catalog", "plot_figure1b_tsne_stage_lncrna.py", code_1b))

    if not args.skip_supplement_pca:
        code_pca = run_supplement_script(
            "plot_supplement_pca_stage_samples.py",
            [
                "--out-dir",
                str(FIGURES_SUPPLEMENTARY_PCA),
                *pub_flags,
            ],
        )
        if code_pca != 0:
            failures.append(("supplement", "plot_supplement_pca_stage_samples.py", code_pca))

    for mode in modes:
        if mode == "all_smprot_filtered" and not ALL_FILTERED_FAA.exists():
            print(
                f"Skip {mode}: missing {ALL_FILTERED_FAA}\n"
                "  Build with: python pipeline/export_tcga_filtered_peptides_fasta.py "
                "--peptides-tsv data/smprot_filtered.tsv --out-aa data/smprot_all_filtered_peptides.faa"
            )
            if args.strict:
                print(f"Missing required FASTA: {ALL_FILTERED_FAA}", file=sys.stderr)
                sys.exit(1)
            continue

        for script, extra in (
            ("plot_tr_de_peptide_fractions_by_transition.py", ["--peptide-gene-set", mode]),
            ("plot_aa_frequency_tcga_vs_proteome.py", ["--peptide-set", mode]),
            ("plot_dipeptide_volcano_lnc_vs_proteome.py", ["--peptide-set", mode]),
        ):
            code = run_script(script, [*extra, *pub_flags])
            if code != 0:
                failures.append((mode, script, code))

    code_3cd = run_script("plot_figure3cd_dipeptide_log2fc_heatmaps.py", pub_flags)
    if code_3cd != 0:
        failures.append(("catalog", "plot_figure3cd_dipeptide_log2fc_heatmaps.py", code_3cd))

    code_4a = run_script("plot_figure4a_tis_vs_ribo_tr_mps.py", pub_flags)
    if code_4a != 0:
        failures.append(("catalog", "plot_figure4a_tis_vs_ribo_tr_mps.py", code_4a))

    if not args.skip_netmhc:
        code = run_script("plot_fig5abc_netmhc_sb_triple.py", pub_flags)
        if code != 0:
            failures.append(("netmhc", "plot_fig5abc_netmhc_sb_triple.py", code))
        code = run_script(
            "plot_fig5abc_netmhc_sb_triple.py",
            [
                "--panels",
                "c",
                "--coding-tsv",
                str(NETMHC_DATA / "netmhcpan_coding_control_with_iedb.tsv"),
                "--output-stem",
                "figS5c_random_fragments",
                "--repo-mirror-dir",
                str(FIGURES_SUPPLEMENTARY_NETMHC_CODING_FRAGMENTS),
                *pub_flags,
            ],
        )
        if code != 0:
            failures.append(("netmhc", "plot_fig5abc_netmhc_sb_triple.py (5C fragments)", code))
        code = run_script(
            "plot_fig5de_merged_iedb_sb_per_allele.py",
            [
                "--coding-tsv",
                str(NETMHC_DATA / "netmhcpan_coding_proportional_whole_with_iedb.tsv"),
                "--output-stem",
                "fig5de_merged_whole",
                *pub_flags,
            ],
        )
        if code != 0:
            failures.append(("netmhc", "plot_fig5de_merged_iedb_sb_per_allele.py (whole)", code))
        code = run_script(
            "plot_fig5de_merged_iedb_sb_per_allele.py",
            [
                "--coding-tsv",
                str(NETMHC_DATA / "netmhcpan_coding_control_with_iedb.tsv"),
                "--output-stem",
                "figS5de_random_fragments",
                "--repo-mirror-dir",
                str(FIGURES_SUPPLEMENTARY_NETMHC_CODING_FRAGMENTS),
                *pub_flags,
            ],
        )
        if code != 0:
            failures.append(("netmhc", "plot_fig5de_merged_iedb_sb_per_allele.py (fragments)", code))

        ttn_out = FIGURES / "fig6_ttn_as1_split.png"
        code = run_script(
            "plot_figure6_ttn_as1_allele_coverage.py",
            [
                "--split-panels",
                "-o",
                str(ttn_out),
                *pub_flags,
            ],
        )
        if code != 0:
            failures.append(("netmhc", "plot_figure6_ttn_as1_allele_coverage.py (instances)", code))

        if args.include_fig6_unique_split:
            FIGURES_SUPPLEMENTARY_FIG6_TTN.mkdir(parents=True, exist_ok=True)
            ttn_unique = FIGURES_SUPPLEMENTARY_FIG6_TTN / "fig6_ttn_as1_split.png"
            code_u = run_script(
                "plot_figure6_ttn_as1_allele_coverage.py",
                [
                    "--split-panels",
                    "--coverage-output",
                    "unique",
                    "-o",
                    str(ttn_unique),
                    *pub_flags,
                ],
            )
            if code_u != 0:
                failures.append(("netmhc", "plot_figure6_ttn_as1_allele_coverage.py (unique)", code_u))

    if failures and args.strict:
        print("Failures:", failures, file=sys.stderr)
        sys.exit(1)
    if failures:
        print("Completed with non-fatal failures:", failures)
    else:
        print("Publication exports done under", FIGURES_PUBLICATION)


if __name__ == "__main__":
    main()
